rm MD5SUMS
rm MD5SUMS.gpg
rm SHA1SUMS
rm SHA1SUMS.gpg
rm SHA256SUMS
rm SHA256SUMS.gpg
rm build-info.txt
rm ubuntu-lunar-core-cloudimg-amd64-root.tar.gz
rm ubuntu-lunar-core-cloudimg-amd64.manifest

wget https://partner-images.canonical.com/core/lunar/current/MD5SUMS
wget https://partner-images.canonical.com/core/lunar/current/MD5SUMS.gpg
wget https://partner-images.canonical.com/core/lunar/current/SHA1SUMS
wget https://partner-images.canonical.com/core/lunar/current/SHA1SUMS.gpg
wget https://partner-images.canonical.com/core/lunar/current/SHA256SUMS
wget https://partner-images.canonical.com/core/lunar/current/SHA256SUMS.gpg
wget https://partner-images.canonical.com/core/lunar/current/ubuntu-lunar-core-cloudimg-amd64-root.tar.gz
wget https://partner-images.canonical.com/core/lunar/current/ubuntu-lunar-core-cloudimg-amd64.manifest
wget https://partner-images.canonical.com/core/lunar/current/unpacked/build-info.txt
